package com.drs.ai.data.db

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Smart reminder. All data stays on device; alarms fire locally via AlarmManager.
 */
@Entity(tableName = "reminders")
data class Reminder(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String,
    val note: String = "",
    val triggerAt: Long,             // epoch millis of next occurrence
    val repeatMode: Int = REPEAT_ONCE, // REPEAT_*
    val intervalMillis: Long = 0,    // for REPEAT_CUSTOM
    val enabled: Boolean = true,
    val createdAt: Long = System.currentTimeMillis(),
    val aiSuggested: Boolean = false  // true when generated by the on-device model
) {
    companion object {
        const val REPEAT_ONCE = 0
        const val REPEAT_DAILY = 1
        const val REPEAT_WEEKLY = 2
        const val REPEAT_CUSTOM = 3

        fun repeatLabel(mode: Int, intervalMillis: Long): String = when (mode) {
            REPEAT_ONCE -> ""
            REPEAT_DAILY -> "daily"
            REPEAT_WEEKLY -> "weekly"
            REPEAT_CUSTOM -> "every ${humanizeInterval(intervalMillis)}"
            else -> ""
        }

        fun humanizeInterval(ms: Long): String {
            val minutes = ms / 60000
            return when {
                minutes >= 1440 -> "${minutes / 1440}d"
                minutes >= 60 -> "${minutes / 60}h"
                else -> "${minutes}m"
            }
        }
    }
}
